TestGuru/config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'gists#create'
    end
  end

  namespace :admin do
    resources :badges, only: %i[index new create destroy]
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: :create
  get 'feedbacks', to: 'feedbacks#new', as: 'new_feedback'

  resources :badges, only: :index
  get 'my_badges', to: 'badges#my_badges', as: 'my_badges'
end

TestGuru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

TestGuru/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to [:admin, @question]
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_question_not_found
    render plain: 'Question not found'
  end
end

TestGuru/app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    return "Create New #{question.test.title} Question" if question.new_record?

    "Edit #{question.test.title} Question"
  end
end

TestGuru/app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, test, question] do |form| %>
  <%= render 'shared/errors', resource: @question %>
  
  <p>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </p>

  <p><%= form.submit %></p>
  
<% end %>

TestGuru/app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('.show'), admin_question_path(question) %></td>
  <td><%= link_to t('.edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('.delete'),
                admin_question_path(question),
                method: :delete,
                data: { confirm: t('.confirm') } %>
  </td>
</tr>

TestGuru/app/views/admin/questions/edit.html.erb
<h1><%= t(".header", test: @question.test.title) %></h1>

<%= render 'form', test: @test, question: @question %>

TestGuru/app/views/admin/questions/index.html.erb
<h1>Questions</h1>

<table>
  <tr>
  <th>Body</th>
  <th colspan="3">Actions</th>
  </tr>
  <%= render @questions %>
</table>

<p><%= button_to "Add question", new_admin_test_question_path(@test), method: :get %></p>

TestGuru/app/views/admin/questions/new.html.erb
<h1><%= t(".header", test: @question.test.title) %></h1>

<%= render 'form', test: @test, question: @question %>

TestGuru/app/views/admin/questions/show.html.erb
<h1><%= t(".header") %></h1>

<p>
  <%=  @question.body %>
</p>

<h2><%= t(".answers") %></h2>

<p>
<%= link_to t(".new_answers"), new_admin_question_answer_path(@question) %>
</p>

<table>
	<tr>
    <th><%= t(".body") %></th>
    <th colspan="3"><%= t(".actions") %></th>
	</tr>
  <%= render @question.answers %>
<table>

<p>
  <%= link_to t(".back"), admin_test_path(@question.test) %>
  <%= link_to t(".edit"), edit_admin_question_path(@question) %>
</p>