TestGuru/config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'gists#create'
    end
  end

  namespace :admin do
    resources :badges, only: %i[index new create destroy]
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: :create
  get 'feedbacks', to: 'feedbacks#new', as: 'new_feedback'

  resources :badges, only: :index
  get 'my_badges', to: 'badges#my_badges', as: 'my_badges'
end

TestGuru/app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
end

TestGuru/app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: :destroy

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success')
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :rule, :value, :image_url)
  end
end

TestGuru/app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def my_badges
    @badges = current_user.badges
  end
end

TestGuru/app/helpers/badges_helper.rb
module BadgesHelper
end

TestGuru/app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= badge.rule %></td>
  <td><%= badge.value %></td>
  <td><%= image_tag("#{badge.image_url}") %></td>
  <td>
    <%= link_to t('.delete'), admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.confirm') } %>
  </td>
</tr>

TestGuru/app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :rule %>
    <%= form.text_field :rule, id: :badge_rule %>
  </p>

  <p>
    <%= form.label :value %>
    <%= form.text_field :value, id: :badge_value %>
  </p>

  <p>
    <%= form.label :image_url %>
    <%= form.url_field :image_url, id: :badge_image_url %>
  </p>
  <p><%= form.submit %></p>
<% end %>

TestGuru/app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= link_to t('.create'), new_admin_badge_path %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class='table'>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.rule') %></th>
    <th><%= t('.value') %></th>
    <th><%= t('.image_url') %></th>
    <th><%= t('.action') %></th>
  </tr>
  <%= render @badges %>
</table>

<%= link_to t('.back'), admin_tests_path %>

TestGuru/app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_tests_path %>