TestGuru/config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'gists#create'
    end
  end

  namespace :admin do
    resources :badges, only: %i[index new create destroy]
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: :create
  get 'feedbacks', to: 'feedbacks#new', as: 'new_feedback'

  resources :badges, only: :index
  get 'my_badges', to: 'badges#my_badges', as: 'my_badges'
end

TestGuru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:question) if question.answers.count >= 4
  end
end

TestGuru/app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: 'Answer was successfully updated.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

TestGuru/app/helpers/answers_helper.rb
module AnswersHelper
end

TestGuru/app/views/admin/answers/_answer.html.erb
<tr> 
	<td><%= answer.body %> 
	<td><%= link_to t('.show'), admin_answer_path(answer) %> | </td>
	<td><%= link_to t('.edit'), edit_admin_answer_path(answer) %> | </td>
	<td>
		<%= link_to t('.delete'), admin_answer_path(answer),
							method: :delete,
							data: { confirm: t('.confirm') } %> </td>
</tr>

TestGuru/app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %>

    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

TestGuru/app/views/admin/answers/edit.html.erb
<h1><%= t(".header") %></h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>
<%= link_to t(".back"), admin_question_path(@answer.question) %>

TestGuru/app/views/admin/answers/new.html.erb
<h1><%= t(".header") %></h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form', answer: @answer %>
<%= link_to t(".back"), admin_question_path(@question) %>

TestGuru/app/views/admin/answers/show.html.erb
<h1><%= t(".header") %></h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t(".answer") %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t(".correct") %></b>
  <%= @answer.correct %>
</p>

<%= link_to t(".back"), admin_question_path(@answer.question) %>