TestGuru/config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist, to: 'gists#create'
    end
  end

  namespace :admin do
    resources :badges, only: %i[index new create destroy]
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: :create
  get 'feedbacks', to: 'feedbacks#new', as: 'new_feedback'

  resources :badges, only: :index
  get 'my_badges', to: 'badges#my_badges', as: 'my_badges'
end

TestGuru/app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

TestGuru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:question) if question.answers.count >= 4
  end
end

TestGuru/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TestGuru/app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
end

TestGuru/app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

TestGuru/app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :name,  presence: true
  validates :email, presence: true
  validates :body,  presence: true
end

TestGuru/app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

TestGuru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

TestGuru/app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :sort_by_category, lambda { |category_name|
    joins(:category).where(categories: { title: category_name }).order(title: :desc)
  }

  scope :by_category, lambda { |category_name|
    joins(:category).where('categories.title = ?', category_name)
  }

  def self.sort_tests_by_category
    sort_by_category.pluck(:title)
  end
end

TestGuru/app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: %i[create update]

  PASSING_PERCENTAGE = 85

  def completed?
    current_question.nil? || time_is_up?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def calculate_percentage
    (correct_questions.to_f / test.questions.count) * 100
  end

  def passed?
    (calculate_percentage >= PASSING_PERCENTAGE)
  end

  def result
    self.passed = passed?

    save!
  end

  def current_question_number
    test.questions.ids.find_index(current_question.id) + 1
  end

  def time_is_up?
    (completion_time.to_i - Time.now.to_i).negative?
  end

  def completion_time
    created_at + (test.timer * 60)
  end

  private

  def set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_validation_set_current_question
    return self.current_question = set_first_question if current_question.nil?

    self.current_question = next_question
  end
end

TestGuru/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_for_tests, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: URI::MailTo::EMAIL_REGEXP, uniqueness: { case_sensitive: false }

  def select_test_by_level(level)
    tests.where(tests: { level: level })
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def user_success_tests
    tests.where(test_passages: { passed: true })
  end

  def user_badges_by_rule(rule)
    user_badges.joins(:badge).where(badge: { rule: rule })
  end
end

TestGuru/app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

TestGuru/app/helpers/answers_helper.rb
module AnswersHelper
end

TestGuru/app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to('TestGuru', "https://github.com/#{author}/#{repo}", target: '_blank', rel: %w[nofollow noopener])
  end
end

TestGuru/app/helpers/badges_helper.rb
module BadgesHelper
end

TestGuru/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

TestGuru/app/helpers/gists_helper.rb
module GistsHelper
end

TestGuru/app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    return "Create New #{question.test.title} Question" if question.new_record?

    "Edit #{question.test.title} Question"
  end
end

TestGuru/app/helpers/sessions_helper.rb
module SessionsHelper
end

TestGuru/app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze  

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

TestGuru/app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand'%>
  
  <span class="navbar-text">
    <%= t('.welcom') %>, <b><%= current_user.email %></b> |
    <%= link_to t('.badges'), admin_badges_path %> |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
  </span>
</nav>

TestGuru/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>
    </body>
</html>

TestGuru/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

TestGuru/app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <div>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= t('.header', count: resource.errors.count) %>:</h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% end %>

TestGuru/app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <% if key == "alert" %>
    <%= content_tag :p, message.html_safe, class: "alert-danger" %>
  <% else %>
    <%= content_tag :p, message.html_safe, class: "alert-primary" %>
  <% end %>
<% end %>

TestGuru/app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light">
  <footer>
    <a class="navbar-text"> <%= t(".project") %> <%= github_url('crrafterr', 'rails_code') %> |
     <%= t(".description") %>|
     <%= link_to t(".link"), "https://thinknetica.com/", target: '_blank', rel: %w[nofollow noopener]%> | 
     <%= link_to t('.feedback'), new_feedback_path %></a>
    <p><%= t(".year") %> <%= current_year %></p>
  </footer>
</nav>

TestGuru/app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %> 
  
  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t(".welcom") %>, <b><%= current_user.email %></b> |
      <%= link_to_if(current_user.is_a?(Admin), t('.adminpanel'), { controller: "admin/tests", action: "index" }) %> |
      <%= link_to t('.badges'), my_badges_path %> |
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> |
      <%= link_to t('.signup'), new_user_registration_path %>
    <% end %>
  </span>
</nav>

TestGuru/app/views/shared/_timer.html.erb
<p><%= content_tag :span, 
                   @test_passage.test.timer,
                   id: 'timer',
                   data: { completion_time: @test_passage.completion_time }%>
</p>